/**
 * generated by Xtext 2.12.0
 */
package org.upct.patterns.observer.observer.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.upct.patterns.observer.observer.Observer;
import org.upct.patterns.observer.observer.ObserverPackage;
import org.upct.patterns.observer.observer.Observers;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Observers</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.upct.patterns.observer.observer.impl.ObserversImpl#getObservers <em>Observers</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ObserversImpl extends TypeImpl implements Observers
{
  /**
   * The cached value of the '{@link #getObservers() <em>Observers</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getObservers()
   * @generated
   * @ordered
   */
  protected EList<Observer> observers;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ObserversImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ObserverPackage.Literals.OBSERVERS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Observer> getObservers()
  {
    if (observers == null)
    {
      observers = new EObjectContainmentEList<Observer>(Observer.class, this, ObserverPackage.OBSERVERS__OBSERVERS);
    }
    return observers;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ObserverPackage.OBSERVERS__OBSERVERS:
        return ((InternalEList<?>)getObservers()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ObserverPackage.OBSERVERS__OBSERVERS:
        return getObservers();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ObserverPackage.OBSERVERS__OBSERVERS:
        getObservers().clear();
        getObservers().addAll((Collection<? extends Observer>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ObserverPackage.OBSERVERS__OBSERVERS:
        getObservers().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ObserverPackage.OBSERVERS__OBSERVERS:
        return observers != null && !observers.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ObserversImpl
