/**
 * generated by Xtext 2.12.0
 */
package org.upct.patterns.observer.observer.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.upct.patterns.observer.observer.ObserverPackage;
import org.upct.patterns.observer.observer.Subject;
import org.upct.patterns.observer.observer.Subjects;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Subjects</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.upct.patterns.observer.observer.impl.SubjectsImpl#getSubjects <em>Subjects</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SubjectsImpl extends TypeImpl implements Subjects
{
  /**
   * The cached value of the '{@link #getSubjects() <em>Subjects</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSubjects()
   * @generated
   * @ordered
   */
  protected EList<Subject> subjects;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SubjectsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ObserverPackage.Literals.SUBJECTS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Subject> getSubjects()
  {
    if (subjects == null)
    {
      subjects = new EObjectContainmentEList<Subject>(Subject.class, this, ObserverPackage.SUBJECTS__SUBJECTS);
    }
    return subjects;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ObserverPackage.SUBJECTS__SUBJECTS:
        return ((InternalEList<?>)getSubjects()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ObserverPackage.SUBJECTS__SUBJECTS:
        return getSubjects();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ObserverPackage.SUBJECTS__SUBJECTS:
        getSubjects().clear();
        getSubjects().addAll((Collection<? extends Subject>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ObserverPackage.SUBJECTS__SUBJECTS:
        getSubjects().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ObserverPackage.SUBJECTS__SUBJECTS:
        return subjects != null && !subjects.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //SubjectsImpl
