/**
 * generated by Xtext 2.12.0
 */
package org.upct.patterns.observer.observer;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Observer</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.upct.patterns.observer.observer.Observer#getObserver <em>Observer</em>}</li>
 * </ul>
 *
 * @see org.upct.patterns.observer.observer.ObserverPackage#getObserver()
 * @model
 * @generated
 */
public interface Observer extends EObject
{
  /**
   * Returns the value of the '<em><b>Observer</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Observer</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Observer</em>' containment reference.
   * @see #setObserver(ElementType)
   * @see org.upct.patterns.observer.observer.ObserverPackage#getObserver_Observer()
   * @model containment="true"
   * @generated
   */
  ElementType getObserver();

  /**
   * Sets the value of the '{@link org.upct.patterns.observer.observer.Observer#getObserver <em>Observer</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Observer</em>' containment reference.
   * @see #getObserver()
   * @generated
   */
  void setObserver(ElementType value);

} // Observer
