/**
 * generated by Xtext 2.12.0
 */
package org.upct.patterns.observer.observer;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.upct.patterns.observer.observer.ObserverFactory
 * @model kind="package"
 * @generated
 */
public interface ObserverPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "observer";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.upct.org/patterns/observer/Observer";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "observer";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ObserverPackage eINSTANCE = org.upct.patterns.observer.observer.impl.ObserverPackageImpl.init();

  /**
   * The meta object id for the '{@link org.upct.patterns.observer.observer.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.upct.patterns.observer.observer.impl.ModelImpl
   * @see org.upct.patterns.observer.observer.impl.ObserverPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.upct.patterns.observer.observer.impl.TypeImpl <em>Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.upct.patterns.observer.observer.impl.TypeImpl
   * @see org.upct.patterns.observer.observer.impl.ObserverPackageImpl#getType()
   * @generated
   */
  int TYPE = 1;

  /**
   * The number of structural features of the '<em>Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.upct.patterns.observer.observer.impl.SubjectsImpl <em>Subjects</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.upct.patterns.observer.observer.impl.SubjectsImpl
   * @see org.upct.patterns.observer.observer.impl.ObserverPackageImpl#getSubjects()
   * @generated
   */
  int SUBJECTS = 2;

  /**
   * The feature id for the '<em><b>Subjects</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBJECTS__SUBJECTS = TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Subjects</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBJECTS_FEATURE_COUNT = TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.upct.patterns.observer.observer.impl.ObserversImpl <em>Observers</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.upct.patterns.observer.observer.impl.ObserversImpl
   * @see org.upct.patterns.observer.observer.impl.ObserverPackageImpl#getObservers()
   * @generated
   */
  int OBSERVERS = 3;

  /**
   * The feature id for the '<em><b>Observers</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBSERVERS__OBSERVERS = TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Observers</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBSERVERS_FEATURE_COUNT = TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.upct.patterns.observer.observer.impl.SubjectImpl <em>Subject</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.upct.patterns.observer.observer.impl.SubjectImpl
   * @see org.upct.patterns.observer.observer.impl.ObserverPackageImpl#getSubject()
   * @generated
   */
  int SUBJECT = 4;

  /**
   * The feature id for the '<em><b>Subject</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBJECT__SUBJECT = 0;

  /**
   * The number of structural features of the '<em>Subject</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBJECT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.upct.patterns.observer.observer.impl.ObserverImpl <em>Observer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.upct.patterns.observer.observer.impl.ObserverImpl
   * @see org.upct.patterns.observer.observer.impl.ObserverPackageImpl#getObserver()
   * @generated
   */
  int OBSERVER = 5;

  /**
   * The feature id for the '<em><b>Observer</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBSERVER__OBSERVER = 0;

  /**
   * The number of structural features of the '<em>Observer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBSERVER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.upct.patterns.observer.observer.impl.ElementTypeImpl <em>Element Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.upct.patterns.observer.observer.impl.ElementTypeImpl
   * @see org.upct.patterns.observer.observer.impl.ObserverPackageImpl#getElementType()
   * @generated
   */
  int ELEMENT_TYPE = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_TYPE__NAME = 0;

  /**
   * The number of structural features of the '<em>Element Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_TYPE_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.upct.patterns.observer.observer.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.upct.patterns.observer.observer.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.upct.patterns.observer.observer.Model#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.upct.patterns.observer.observer.Model#getElements()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Elements();

  /**
   * Returns the meta object for class '{@link org.upct.patterns.observer.observer.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type</em>'.
   * @see org.upct.patterns.observer.observer.Type
   * @generated
   */
  EClass getType();

  /**
   * Returns the meta object for class '{@link org.upct.patterns.observer.observer.Subjects <em>Subjects</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Subjects</em>'.
   * @see org.upct.patterns.observer.observer.Subjects
   * @generated
   */
  EClass getSubjects();

  /**
   * Returns the meta object for the containment reference list '{@link org.upct.patterns.observer.observer.Subjects#getSubjects <em>Subjects</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Subjects</em>'.
   * @see org.upct.patterns.observer.observer.Subjects#getSubjects()
   * @see #getSubjects()
   * @generated
   */
  EReference getSubjects_Subjects();

  /**
   * Returns the meta object for class '{@link org.upct.patterns.observer.observer.Observers <em>Observers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Observers</em>'.
   * @see org.upct.patterns.observer.observer.Observers
   * @generated
   */
  EClass getObservers();

  /**
   * Returns the meta object for the containment reference list '{@link org.upct.patterns.observer.observer.Observers#getObservers <em>Observers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Observers</em>'.
   * @see org.upct.patterns.observer.observer.Observers#getObservers()
   * @see #getObservers()
   * @generated
   */
  EReference getObservers_Observers();

  /**
   * Returns the meta object for class '{@link org.upct.patterns.observer.observer.Subject <em>Subject</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Subject</em>'.
   * @see org.upct.patterns.observer.observer.Subject
   * @generated
   */
  EClass getSubject();

  /**
   * Returns the meta object for the containment reference '{@link org.upct.patterns.observer.observer.Subject#getSubject <em>Subject</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Subject</em>'.
   * @see org.upct.patterns.observer.observer.Subject#getSubject()
   * @see #getSubject()
   * @generated
   */
  EReference getSubject_Subject();

  /**
   * Returns the meta object for class '{@link org.upct.patterns.observer.observer.Observer <em>Observer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Observer</em>'.
   * @see org.upct.patterns.observer.observer.Observer
   * @generated
   */
  EClass getObserver();

  /**
   * Returns the meta object for the containment reference '{@link org.upct.patterns.observer.observer.Observer#getObserver <em>Observer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Observer</em>'.
   * @see org.upct.patterns.observer.observer.Observer#getObserver()
   * @see #getObserver()
   * @generated
   */
  EReference getObserver_Observer();

  /**
   * Returns the meta object for class '{@link org.upct.patterns.observer.observer.ElementType <em>Element Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element Type</em>'.
   * @see org.upct.patterns.observer.observer.ElementType
   * @generated
   */
  EClass getElementType();

  /**
   * Returns the meta object for the attribute '{@link org.upct.patterns.observer.observer.ElementType#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.upct.patterns.observer.observer.ElementType#getName()
   * @see #getElementType()
   * @generated
   */
  EAttribute getElementType_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ObserverFactory getObserverFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.upct.patterns.observer.observer.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.upct.patterns.observer.observer.impl.ModelImpl
     * @see org.upct.patterns.observer.observer.impl.ObserverPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ELEMENTS = eINSTANCE.getModel_Elements();

    /**
     * The meta object literal for the '{@link org.upct.patterns.observer.observer.impl.TypeImpl <em>Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.upct.patterns.observer.observer.impl.TypeImpl
     * @see org.upct.patterns.observer.observer.impl.ObserverPackageImpl#getType()
     * @generated
     */
    EClass TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '{@link org.upct.patterns.observer.observer.impl.SubjectsImpl <em>Subjects</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.upct.patterns.observer.observer.impl.SubjectsImpl
     * @see org.upct.patterns.observer.observer.impl.ObserverPackageImpl#getSubjects()
     * @generated
     */
    EClass SUBJECTS = eINSTANCE.getSubjects();

    /**
     * The meta object literal for the '<em><b>Subjects</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUBJECTS__SUBJECTS = eINSTANCE.getSubjects_Subjects();

    /**
     * The meta object literal for the '{@link org.upct.patterns.observer.observer.impl.ObserversImpl <em>Observers</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.upct.patterns.observer.observer.impl.ObserversImpl
     * @see org.upct.patterns.observer.observer.impl.ObserverPackageImpl#getObservers()
     * @generated
     */
    EClass OBSERVERS = eINSTANCE.getObservers();

    /**
     * The meta object literal for the '<em><b>Observers</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBSERVERS__OBSERVERS = eINSTANCE.getObservers_Observers();

    /**
     * The meta object literal for the '{@link org.upct.patterns.observer.observer.impl.SubjectImpl <em>Subject</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.upct.patterns.observer.observer.impl.SubjectImpl
     * @see org.upct.patterns.observer.observer.impl.ObserverPackageImpl#getSubject()
     * @generated
     */
    EClass SUBJECT = eINSTANCE.getSubject();

    /**
     * The meta object literal for the '<em><b>Subject</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUBJECT__SUBJECT = eINSTANCE.getSubject_Subject();

    /**
     * The meta object literal for the '{@link org.upct.patterns.observer.observer.impl.ObserverImpl <em>Observer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.upct.patterns.observer.observer.impl.ObserverImpl
     * @see org.upct.patterns.observer.observer.impl.ObserverPackageImpl#getObserver()
     * @generated
     */
    EClass OBSERVER = eINSTANCE.getObserver();

    /**
     * The meta object literal for the '<em><b>Observer</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBSERVER__OBSERVER = eINSTANCE.getObserver_Observer();

    /**
     * The meta object literal for the '{@link org.upct.patterns.observer.observer.impl.ElementTypeImpl <em>Element Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.upct.patterns.observer.observer.impl.ElementTypeImpl
     * @see org.upct.patterns.observer.observer.impl.ObserverPackageImpl#getElementType()
     * @generated
     */
    EClass ELEMENT_TYPE = eINSTANCE.getElementType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMENT_TYPE__NAME = eINSTANCE.getElementType_Name();

  }

} //ObserverPackage
