/**
 * generated by Xtext 2.12.0
 */
package org.upct.patterns.observer.observer;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Subject</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.upct.patterns.observer.observer.Subject#getSubject <em>Subject</em>}</li>
 * </ul>
 *
 * @see org.upct.patterns.observer.observer.ObserverPackage#getSubject()
 * @model
 * @generated
 */
public interface Subject extends EObject
{
  /**
   * Returns the value of the '<em><b>Subject</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Subject</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Subject</em>' containment reference.
   * @see #setSubject(ElementType)
   * @see org.upct.patterns.observer.observer.ObserverPackage#getSubject_Subject()
   * @model containment="true"
   * @generated
   */
  ElementType getSubject();

  /**
   * Sets the value of the '{@link org.upct.patterns.observer.observer.Subject#getSubject <em>Subject</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Subject</em>' containment reference.
   * @see #getSubject()
   * @generated
   */
  void setSubject(ElementType value);

} // Subject
