/*
 * generated by Xtext 2.12.0
 */
package org.upct.patterns.observer


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ObserverStandaloneSetup extends ObserverStandaloneSetupGenerated {

	def static void doSetup() {
		new ObserverStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
