/*
 * generated by Xtext 2.12.0
 */
package org.upct.patterns.observer


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ObserverRuntimeModule extends AbstractObserverRuntimeModule {
}
