/*
 * generated by Xtext 2.12.0
 */
package org.upct.patterns.observer.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractObserverScopeProvider extends DelegatingScopeProvider {
}
