/**
 * generated by Xtext 2.12.0
 */
package org.upct.patterns.observer;

import org.upct.patterns.observer.AbstractObserverRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ObserverRuntimeModule extends AbstractObserverRuntimeModule {
}
