/**
 * generated by Xtext 2.12.0
 */
package org.upct.patterns.observer;

import org.upct.patterns.observer.ObserverStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ObserverStandaloneSetup extends ObserverStandaloneSetupGenerated {
  public static void doSetup() {
    new ObserverStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
