/*
 * generated by Xtext 2.12.0
 */
package org.upct.patterns.observer.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ObserverAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/upct/patterns/observer/parser/antlr/internal/InternalObserver.tokens");
	}
}
