/**
 * generated by Xtext 2.12.0
 */
package org.upct.patterns.observer.validation;

import org.upct.patterns.observer.validation.AbstractObserverValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ObserverValidator extends AbstractObserverValidator {
}
